spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pg2c
    username: root
    password: root
  jpa:
    show-sql: true
  application:
    name: Accounts project
server:
  port: 9000
  servlet:
    context-path: /api/acc
